name: Linting Check

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  check-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install packages
        run: bun install

      - name: Check linting
        run: bun run lint
